version: "3.8"

services:
<<<<<<< HEAD
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
=======
  app-prod:
    image: "${APP_IMAGE}:${APP_TAG}"
>>>>>>> 0ee0edf (initial commit)
    restart: always
    ports:
      - 5000:5000
    env_file:
      - .env
<<<<<<< HEAD
    depends_on:
      - database
=======
    networks:
      - absensi

  app-staging:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5001:5000
    env_file:
      - .env
    networks:
      - absensi

  app-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - 5002:5000
    env_file:
      - .env
>>>>>>> 0ee0edf (initial commit)
    networks:
      - absensi

  database:
    container_name: database
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - absensi

networks:
  absensi:

volumes:
  pgdata: